import sys
import os
import torch
import numpy as np
import cv2  
from PyQt6.QtCore import QThread, pyqtSignal, Qt, QTimer
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import (QApplication, QMainWindow, QFileDialog, QVBoxLayout,
                             QHBoxLayout, QWidget, QGridLayout, QProgressBar,
                             QLabel, QPushButton, QStackedWidget)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import pydicom

# Nạp đường dẫn source code
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))
from mri_analyzer import analyze_mri_unet
from unet_model import UNet

# ====================== Canvas hiển thị MRI (U-Net Segmentation) ======================
class MRICanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.fig = Figure(figsize=(10, 5), facecolor='white')
        self.ax_orig = self.fig.add_subplot(121)
        self.ax_heat = self.fig.add_subplot(122)
        self.fig.tight_layout(pad=2.0)
        super().__init__(self.fig)

    def plot_image(self, img_with_boxes, heatmap, title=""):
        self.ax_orig.clear()
        self.ax_heat.clear()
        
        self.ax_orig.imshow(img_with_boxes)
        self.ax_orig.set_title(f"MRI & Suspected Regions\n[File: {title}]", fontsize=11, fontweight='bold', color='#2c3e50')
        self.ax_orig.tick_params(axis='both', labelsize=8)
        self.ax_orig.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.5)
        
        self.ax_heat.imshow(heatmap)
        self.ax_heat.set_title(f"AI Segmentation Mask (U-Net)\n[File: {title}]", fontsize=11, fontweight='bold', color='#2c3e50')
        self.ax_heat.tick_params(axis='both', labelsize=8)
        self.ax_heat.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.5)
        
        self.draw()

# ====================== Worker xử lý MRI ======================
class MRIPredictWorker(QThread):
    progress = pyqtSignal(int)
    done = pyqtSignal(str, np.ndarray, np.ndarray, str) 

    def __init__(self, file_path):
        super().__init__()
        self.file_path = file_path

    def run(self):
        try:
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            
            # 1. Load mô hình U-Net siêu việt bạn vừa train
            model = UNet(in_channels=1, out_channels=1).to(device)
            model.load_state_dict(torch.load("models/unet_best.pth", map_location=device))
            model.eval()

            # 2. Đọc linh hoạt DICOM & JPG/PNG
            ext = self.file_path.lower()
            if ext.endswith(('.ima', '.dcm')):
                ds = pydicom.dcmread(self.file_path)
                image = ds.pixel_array.astype(np.float32)
                # Chuẩn hóa về 0-255 giống như cv2.imread
                image = (image - image.min()) / (image.max() - image.min() + 1e-8) * 255.0
                image = image.astype(np.uint8)
            else:
                image = cv2.imread(self.file_path, cv2.IMREAD_GRAYSCALE)
                if image is None: raise Exception("Không hỗ trợ định dạng ảnh này.")
                
            if image.ndim == 3:
                image = image[image.shape[0] // 2, :, :]
            
            # 3. Tiền xử lý đúng chuẩn (Giống file unet_dataset.py)
            image_resized = cv2.resize(image, (224, 224), interpolation=cv2.INTER_LINEAR)
            image_normalized = image_resized.astype(np.float32) / 255.0
            
            # Tensor đầu vào cho U-Net [1, 1, 224, 224]
            input_tensor = torch.from_numpy(image_normalized).unsqueeze(0).unsqueeze(0).to(device)

            # Tạo hiệu ứng thanh tiến trình chạy mượt mà
            for i in range(1, 101):
                self.progress.emit(i)
                QThread.msleep(5)

            # 4. Phân tích qua U-Net
            img_with_boxes, heatmap, prob_overall, has_anom, suggestions = analyze_mri_unet(input_tensor, model, image_normalized)

            # 5. Xuất kết quả văn bản
            if has_anom:
                details = "\n".join(suggestions)
                result_text = (f"⚠️ AI DETECTED ABNORMALITY (Average Tumor Confidence: {prob_overall:.1f}%)\n"
                               f"----------------------------------------------------\n"
                               f"{details}\n"
                               f"----------------------------------------------------\n"
                               f"👉 High-precision segmentation mask generated by U-Net.")
            else:
                result_text = (f"✅ NO ABNORMALITY DETECTED\n"
                               f"AI Confidence for normal structure is very high.\n"
                               f"The U-Net model found no pathological features.")

            self.done.emit(result_text, img_with_boxes, heatmap, os.path.basename(self.file_path))
        except Exception as e:
            import traceback
            print(f"Error: {traceback.format_exc()}")
            self.done.emit(f"❌ Processing Error: {str(e)}", np.zeros((224,224,3), dtype=np.uint8), np.zeros((224,224,3), dtype=np.uint8), "Error")

# ====================== Cửa sổ chính ======================
class BrainApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Hệ thống MRI U-Net Segmentation - HCMUT")
        self.resize(1100, 800)
        self.setStyleSheet("background-color: white;")
        self.stack = QStackedWidget()
        self.setCentralWidget(self.stack)

        # ---------- Trang 0: Màn hình chính ----------
        self.home_page = QWidget()
        home_layout = QVBoxLayout(self.home_page)
        home_layout.setContentsMargins(20, 20, 20, 20)

        brain_logo = QLabel()
        pixmap = QPixmap("brain.png")
        if not pixmap.isNull():
            pixmap = pixmap.scaled(120, 120, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)
            brain_logo.setPixmap(pixmap)
        else:
            brain_logo.setText("🧠")
            brain_logo.setStyleSheet("font-size: 80px; color: #2c3e50;")
        brain_logo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        home_layout.addWidget(brain_logo)

        title = QLabel("HỆ THỐNG U-NET KHOANH VÙNG KHỐI U NÃO")
        title.setStyleSheet("font-size: 32px; font-weight: bold; color: #2c3e50; margin: 20px;")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        home_layout.addWidget(title)

        home_layout.addSpacing(30)

        self.btn_mri = QPushButton("📁 NẠP FILE MRI (DICOM / JPG / PNG)")
        self.btn_mri.setFixedSize(400, 80)
        self.btn_mri.setStyleSheet("QPushButton { border: 3px solid #e67e22; border-radius: 20px; font-size: 20px; font-weight: bold; background-color: white; color: #2c3e50; } QPushButton:hover { background-color: #f39c12; color: white; }")
        self.btn_mri.clicked.connect(self.load_mri)
        home_layout.addWidget(self.btn_mri, alignment=Qt.AlignmentFlag.AlignCenter)

        home_layout.addStretch()

        footer = QHBoxLayout()
        dev_label = QLabel("Developed by HCMUTer | Model: PyTorch U-Net")
        dev_label.setStyleSheet("font-size: 16px; color: #7f8c8d;")
        footer.addWidget(dev_label)
        footer.addStretch()
        bku_logo = QLabel()
        bku_pix = QPixmap("bku_logo.png")
        if not bku_pix.isNull():
            bku_logo.setPixmap(bku_pix.scaled(50, 50, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation))
        else:
            bku_logo.setText("BKU")
        bku_logo.setAlignment(Qt.AlignmentFlag.AlignRight)
        footer.addWidget(bku_logo)
        home_layout.addLayout(footer)
        
        self.stack.addWidget(self.home_page)

        # Style cho nút bấm quay lại / thoát
        btn_style = "QPushButton { border: 2px solid #7f8c8d; border-radius: 10px; padding: 12px 30px; font-size: 16px; font-weight: bold; background-color: white; color: black; } QPushButton:hover { background-color: #ecf0f1; }"

        # ---------- Trang 1: Phân tích MRI ----------
        self.mri_page = QWidget()
        mri_layout = QGridLayout(self.mri_page)
        self.mri_canvas = MRICanvas(self)
        mri_layout.addWidget(self.mri_canvas, 0, 0, 1, 3)

        self.mri_progress = QProgressBar()
        self.mri_progress.setStyleSheet("QProgressBar { border: 2px solid #bdc3c7; border-radius: 8px; text-align: center; height: 25px; background-color: white; } QProgressBar::chunk { background-color: #e67e22; border-radius: 8px; }")
        self.mri_progress.setVisible(False)
        mri_layout.addWidget(self.mri_progress, 1, 0, 1, 3)

        self.mri_result = QLabel("")
        self.mri_result.setAlignment(Qt.AlignmentFlag.AlignCenter)
        mri_layout.addWidget(self.mri_result, 2, 0, 1, 3)

        nav_mri = QHBoxLayout()
        btn_back_mri = QPushButton("⬅ Quay lại")
        btn_exit_mri = QPushButton("✖ Thoát")
        btn_back_mri.setStyleSheet(btn_style)
        btn_exit_mri.setStyleSheet(btn_style + "QPushButton:hover { background-color: #e74c3c; color: white; }")
        btn_back_mri.clicked.connect(lambda: self.stack.setCurrentIndex(0))
        btn_exit_mri.clicked.connect(self.close)
        nav_mri.addStretch()
        nav_mri.addWidget(btn_back_mri)
        nav_mri.addWidget(btn_exit_mri)
        mri_layout.addLayout(nav_mri, 3, 0, 1, 3)
        
        mri_layout.setRowStretch(0, 10)
        mri_layout.setRowStretch(2, 1)
        self.stack.addWidget(self.mri_page)

        self.timer = QTimer()
        self.timer.setSingleShot(True)
        self.timer.timeout.connect(self.hide_progress)

    def load_mri(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Chọn file MRI", "", "Image Files (*.ima *.dcm *.jpg *.jpeg *.png)")
        if file_path:
            self.stack.setCurrentIndex(1) # Chuyển sang màn hình MRI (Trang số 1)
            self.mri_progress.setValue(0)
            self.mri_progress.setVisible(True)
            self.mri_result.setText("🔍 Đang chạy mô hình U-Net chuẩn y tế...")
            self.mri_result.setStyleSheet("font-size: 28px; font-weight: bold; color: #e67e22;")

            self.mri_worker = MRIPredictWorker(file_path)
            self.mri_worker.progress.connect(self.mri_progress.setValue)
            self.mri_worker.done.connect(self.show_mri_result)
            self.mri_worker.start()

    def show_mri_result(self, result_text, img_with_boxes, heatmap, file_name):
        if img_with_boxes is not None:
            self.mri_canvas.plot_image(img_with_boxes, heatmap, title=file_name)
        else:
            self.mri_canvas.ax_orig.clear()
            self.mri_canvas.ax_heat.clear()
            self.mri_canvas.ax_orig.text(0.5, 0.5, "Lỗi hiển thị", ha='center', va='center')
            self.mri_canvas.draw()

        self.mri_result.setText(result_text)
        color = "#e74c3c" if "ABNORMALITY" in result_text or "BẤT THƯỜNG" in result_text else "#27ae60"
        self.mri_result.setStyleSheet(f"font-size: 16px; font-weight: bold; color: {color}; margin: 10px;")
        self.timer.start(2000)

    def hide_progress(self):
        self.mri_progress.setVisible(False)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = BrainApp()
    window.show()
    sys.exit(app.exec())